### ISSUE TITLE
请问什么时候可以支持链式结构

### ISSUE THREAD

**Issue by lhj1079947827** [hackware1993/Flutter_ConstraintLayout#12]
请问什么时候才能支持链式结构，链式结构这个布局会时常用到。如view均匀分布，居中，所占权重等等。

**Comment by hackware1993** [comment]
暂时不计划支持，可以用 Flex（Row、Column）实现

**Comment by lhj1079947827** [comment]
行吧，只能暂时这样子来做了。

**Comment by hackware1993** [comment]
使用百分比布局很容易实现均匀分布、权重分布的

**Comment by lhj1079947827** [comment]
你好！能否在文档把基础约束说明写一下。有时候不懂bottomLeftTo属性是什么意思的对其方式。有点懵

**Comment by hackware1993** [comment]
> 你好！能否在文档把基础约束说明写一下。有时候不懂bottomLeftTo属性是什么意思的对其方式。有点懵

https://mp.weixin.qq.com/s/yTpp7TtLagOeWzX2URKOIQ

**Comment by lhj1079947827** [comment]
Flutter_ConstraintLayout放在SingleScrollView里面不能滚动。。。

**Comment by hackware1993** [comment]
> Flutter_ConstraintLayout放在SingleScrollView里面不能滚动。。。

你要把它的高度设置成 wrapContent，贴你的代码看看

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/189256932-99e48410-93ef-4f97-8d0e-49b8468ad1d0.png)
](url)
上面就是一个SingleScrollView

**Comment by lhj1079947827** [comment]
就是这样子的，但是不能滚动

**Comment by lhj1079947827** [comment]
可能是我使用SingleChildScrollView姿势不对，换成ListView就可以了

**Comment by hackware1993** [comment]
ConstraintLayout 默认会撑满父布局，你想让它在 SingleChildScrollView 里可滚动的话，要做两件事情：
1. 限制 SingleChildScrollView 的高度为定值
2. 将 ConstraintLayout 的 height 设置为 wrapContent，其子元素布局时尽量把它撑高

**Comment by lhj1079947827** [comment]
我已经设置了高度为wrapContent，还是不能滚动

**Comment by hackware1993** [comment]
> 我已经设置了高度为wrapContent，还是不能滚动

你的 ConstraintLayout 高度足够高了？

**Comment by lhj1079947827** [comment]
已经足够高了

**Comment by hackware1993** [comment]
把你的代码贴全，我瞅瞅

**Comment by lhj1079947827** [comment]
`@override
  Widget build(BuildContext context) {
    return ListView(
      children: [getContentView()],
    );
  }

  Widget getContentView() {
    return ConstraintLayout(
      height: wrapContent,
      children: [
        Container(
          decoration: BoxDecoration(
            color: AppColors.lightOrangeColor,
            borderRadius:
                BorderRadius.all(Radius.circular(Dimens.value_4.toDouble().r)),
          ),
        ).applyConstraint(
            margin: EdgeInsets.only(
                top: Dimens.value_20.h,
                left: Dimens.value_8.w,
                right: Dimens.value_8.w),
            top: parent.top,
            height: Dimens.value_135.h,
            width: matchParent),
        Container(
          height: Dimens.value_28.h,
          width: Dimens.value_93.w,
          decoration: BoxDecoration(
              color: AppColors.colorWhite,
              border: Border.all(
                  color: AppColors.lightOrangeColor,
                  width: Dimens.value_6.toDouble())),
        ).applyConstraint(
            top: parent.top,
            centerHorizontalTo: parent,
            margin: EdgeInsets.only(top: Dimens.value_8.h)),
        Container(
          child: CommonText.black18Text("早上好",
              color: AppColors.colorWhite, fontSize: Dimens.value_20.sp),
        ).applyConstraint(
            top: rId(0).top,
            left: rId(0).left,
            margin: EdgeInsets.only(
                left: Dimens.value_45.w, top: Dimens.value_28.h)),
        Container(
          child: CommonText.normalText("今日没有工单哦",
              color: AppColors.colorWhite, fontSize: Dimens.value_14.sp),
        ).applyConstraint(
            top: rId(2).bottom,
            bottomLeftTo: rId(2),
            margin: EdgeInsets.only(top: Dimens.value_30.h)),
        Image.asset(
          UIData.imageHomeService,
          width: Dimens.value_54.w,
          height: Dimens.value_50.h,
        ).applyConstraint(
            top: rId(0).top,
            right: rId(0).right,
            margin: EdgeInsets.only(
                top: Dimens.value_36.h, right: Dimens.value_44.w)),
        Container(
          decoration: BoxDecoration(
              color: AppColors.colorWhite,
              borderRadius:
                  BorderRadius.all(Radius.circular(Dimens.value_4.r))),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Image.asset(
                UIData.imageHomePlan,
                width: Dimens.value_34.w,
                height: Dimens.value_34.h,
              ),
              CommonText.normalText("膳食",
                  color: AppColors.mainTextColor, fontSize: Dimens.value_11.sp)
            ],
          ),
        ).applyConstraint(
            top: rId(0).bottom,
            left: rId(0).left,
            width: Dimens.value_168.w,
            height: Dimens.value_80.h,
            margin: EdgeInsets.only(top: Dimens.value_16.h)),
        Container(
          decoration: BoxDecoration(
              color: AppColors.colorWhite,
              borderRadius:
                  BorderRadius.all(Radius.circular(Dimens.value_4.r))),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Image.asset(
                UIData.imageHomeTask,
                width: Dimens.value_34.w,
                height: Dimens.value_34.h,
              ),
              CommonText.normalText("任务",
                  color: AppColors.mainTextColor, fontSize: Dimens.value_11.sp)
            ],
          ),
        ).applyConstraint(
            top: rId(0).bottom,
            right: rId(0).right,
            width: Dimens.value_168.w,
            height: Dimens.value_80.h,
            margin: EdgeInsets.only(top: Dimens.value_16.h)),
        Container(
                decoration: BoxDecoration(
                    color: AppColors.colorWhite,
                    borderRadius:
                        BorderRadius.all(Radius.circular(Dimens.value_2.r))),
                child: BannerView(
                  //子Item构建器
                  itemBuilder: (BuildContext context, int index) {
                    String itemStr = _looperContent[index];
                    //通常可以是一个 Text文本
                    return Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        SizedBox(
                          width: Dimens.value_18.w,
                        ),
                        Image.asset(UIData.imageHomeMessage,
                            width: Dimens.value_14.w,
                            height: Dimens.value_14.w),
                        SizedBox(
                          width: Dimens.value_10.w,
                        ),
                        CommonText.black14Text(itemStr)
                      ],
                    );
                  },
                  //循环的提示消息数量
                  count: _looperContent.length,
                ))
            .applyConstraint(
                top: sId(-1).bottom,
                centerHorizontalTo: parent,
                width: matchConstraint,
                height: Dimens.value_30.h,
                margin: EdgeInsets.only(
                    top: Dimens.value_16.h,
                    right: Dimens.value_8.w,
                    left: Dimens.value_8.w)),
        Container(
          decoration: BoxDecoration(
              color: AppColors.colorWhite,
              borderRadius:
                  BorderRadius.all(Radius.circular(Dimens.value_8.r))),
        ).applyConstraint(
            width: matchConstraint,
            centerHorizontalTo: parent,
            height: 800.h,
            top: sId(-1).bottom,
            margin: EdgeInsets.only(
                top: Dimens.value_16.h,
                right: Dimens.value_8.w,
                left: Dimens.value_8.w)),
      ],
    );
  }`

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/189261829-1f680703-b5a4-42aa-96c6-b8b525e7f712.png)
](url)

**Comment by hackware1993** [comment]
你截个图，我看看真实的展示是长啥样

**Comment by lhj1079947827** [comment]
手机上展示吗？

**Comment by hackware1993** [comment]
看出问题了，最后一个 Containner 的 width 不要用 matchConstrant，去掉 centerHorizontalTo: parent。直接将 width 设置为 matchParent。

你用 matchConstraint，导致实际上没法把 ConstraintLayout 撑高。

**Comment by lhj1079947827** [comment]
会报错

**Comment by lhj1079947827** [comment]
说没有左右约束，如果是这个问题的话，上面还有还几个都是这样子设置的

**Comment by lhj1079947827** [comment]
我设置看看

**Comment by lhj1079947827** [comment]
可以了，确实matchConstraint的原因，谢谢了啊，还有一个问题我设置matchConstraint时候在设置宽度比例为什么会报错呢，

**Comment by hackware1993** [comment]
默认情况下，ConstraintLayout 会撑满父元素。这种情况下使用时不会有什么需要额外注意的地方，但当把它的宽或高设置为 wrapContent 时，情况就不一样了。后面我会写一篇文章来把这个 “坑” 作详细说明。稍等我再给你细细解释一下为什么。

**Comment by lhj1079947827** [comment]
好的

**Comment by hackware1993** [comment]
> 可以了，确实matchConstraint的原因，谢谢了啊，还有一个问题我设置matchConstraint时候在设置宽度比例为什么会报错呢，

报的啥错？

**Comment by lhj1079947827** [comment]
matchConstraint宽度设置为这个，不是还有一个属性设置占比吗，昨天我设置了不起作用

**Comment by lhj1079947827** [comment]
![image](https://user-images.githubusercontent.com/20966610/189264941-4b9d2508-8943-44ea-8e0c-c4b0c228db3b.png)

**Comment by hackware1993** [comment]
把 widthPercentageAnchor 设置为 PercentageAnchor.parent 就好了

**Comment by hackware1993** [comment]
https://mp.weixin.qq.com/s/yTpp7TtLagOeWzX2URKOIQ

**Comment by lhj1079947827** [comment]
能否专门出一个属性说明，和属性互斥的文档说明。这样子我们报错时候可以直接对照你的文档来找问题。

**Comment by lhj1079947827** [comment]
看是不是属性用错了。或者缺少什么属性。或者用了某个属性导致什么问题

**Comment by lhj1079947827** [comment]
因为工作问题，可能没有时间去详细看你的文档。只想找一个专门属性说明的文档来对照就知道问题了。

**Comment by hackware1993** [comment]
![image](https://user-images.githubusercontent.com/6748135/189265353-925ad413-1016-442e-8c7b-0c75a9c23cfa.png)

**Comment by lhj1079947827** [comment]
我有时间仔细去看看这个文档把。谢谢了啊
