### ISSUE TITLE
margin left not work, when centerHorizontalTo parent

### ISSUE THREAD

**Issue by DonaldDu** [hackware1993/Flutter_ConstraintLayout#13]
Widget addressView() {
    return Text(
      '当前位置：地址1111111111111111111100000002222222222222222222222222220000000',
      textAlign: TextAlign.center,
      style: TextStyle(fontSize: 12),
    ).applyConstraint(
      id: address,
      centerHorizontalTo: parent,
      top: center.bottom,
      margin: const EdgeInsets.only(top: 24, left: 50,right: 50),
    );
  }

**Comment by hackware1993** [comment]
左右的 margin 都一样，你用 centerHorizontalTo parent 看不出效果啊
