### ISSUE TITLE
布局约束问题

### ISSUE THREAD

**Issue by lhj1079947827** [hackware1993/Flutter_ConstraintLayout#15]
![image](https://user-images.githubusercontent.com/20966610/189802204-08ebb8a3-b00e-4090-a6f9-0f1ce58a60c2.png)

这个left和right约束有问题
![image](https://user-images.githubusercontent.com/20966610/189802791-5c22e4d9-049f-4ec8-8660-19dd2c203612.png)

**Comment by lhj1079947827** [comment]
如果去掉right: rId(0).right,和效果能达到上面的效果，右边没有约束导致超过屏幕
![image](https://user-images.githubusercontent.com/20966610/189801746-1ccf3472-e0c7-4a19-952f-9599e948bb4b.png)

**Comment by hackware1993** [comment]
显然文字的 width 要用 matchConstraint

**Comment by lhj1079947827** [comment]
谢了
