### ISSUE TITLE
请问这个有对比过在同一布局改写前后的火焰图耗时改变么

### ISSUE THREAD

**Issue by endless7** [hackware1993/Flutter_ConstraintLayout#3]
thx.

**Comment by hackware1993** [comment]
开发效率的提高和代码量的减少是明显感受到的。性能指标目前只是基于代码复杂度分析以及实际性能表现得来的。目前基本上都是在顶层来使用，即一个页面一个 ConstraintLayout。实际表现是在 60 刷新率的手机上轻松达到 60 帧，在 120 刷新率的手机上轻松达到 120 帧。暂时没有专门去构造一个极端复杂页面来做改造前后的对比，因为单向的性能数据就已经非常亮眼了。当然近期有空我会做这个，这样会显得更有说服力。

**Comment by hackware1993** [comment]
我的设计首要目标倒不是改善性能，而是从根本上解决“嵌套地狱”问题，并弥补现有布局构造复杂页面的灵活性问题。Flutter 积极组合的设计几乎没有带来任何好处，反而有很多弊端。

**Comment by jesse996** [comment]
约束没有写对的时候种植台会不断的输出错误信息，希望输出一次错误信息就好

**Comment by hackware1993** [comment]
> 约束没有写对的时候控制台会不断的输出错误信息，希望输出一次错误信息就好

近期会考虑优化，这个主要是 dart 的异常机制导致的，约束不合法抛了异常并不能阻止后续的 layout、paint 过程，导致后面触发了更多异常。
