### ISSUE TITLE
求助一个约束使用问题

### ISSUE THREAD

**Issue by roger66** [hackware1993/Flutter_ConstraintLayout#6]
![Screenshot_1656032843](https://user-images.githubusercontent.com/16676365/175439780-ae1d2854-0a2f-4086-a613-c7f962e13da7.png)
我想让Text2在Text1的右边，并且Text1文字超长的时候不会把Text2挤出屏幕该怎么做，原生android是加互相约束

**Comment by hackware1993** [comment]
那你要限定  Text1 的最大宽度啊

**Comment by hackware1993** [comment]
或者让 Text2 约束在 parent 的右边，Text1 约束在红框和 Text2 之间，width 为 matchConstraint

**Comment by roger66** [comment]
> 或者让 Text2 约束在 parent 的右边，Text1 约束在红框和 Text2 之间，width 为 matchConstraint

   就是想让Text1尽可能的宽，Text2约束在parent的右边是不是一直靠右了

**Comment by hackware1993** [comment]
你不想让 Text2 挤出屏幕，又想让 Text1 尽可能宽，那就只有这种办法

**Comment by roger66** [comment]
在原生android是两个Text加互相约束，在flutter的版本只有单向约束，看来只能限制最大宽度



---原始邮件---
发件人: "fangbing ***@***.***&gt;
发送时间: 2022年6月24日(周五) 上午9:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hackware1993/Flutter_ConstraintLayout] 求助一个约束使用问题 (Issue #6)




 
你不想让 Text2 挤出屏幕，又想让 Text1 尽可能宽，那就只有这种办法
