### ISSUE TITLE
为何每次编译过后build文件夹一堆constraintLayout错误

### ISSUE THREAD

**Issue by roger66** [hackware1993/Flutter_ConstraintLayout#8]
![image](https://user-images.githubusercontent.com/16676365/178439070-b6818327-0844-4df6-82ed-4d7e4c8a789c.png)

**Comment by hackware1993** [comment]
目前 example 没有单独抽离出来，你忽略即可，打包时的 Tree Shaking 机制不会打包这些代码

**Comment by hackware1993** [comment]
你是直接 clone 以后跑的工程吧，用 Git 或 pub 依赖是不会把这些 example 拉下来的啊

**Comment by roger66** [comment]
我是用pub依赖的，每次编译都会往build里面插入example

**Comment by hackware1993** [comment]
奇怪，我这边 Git 和 Pub 依赖都是可以的，我抽空把 example 整理一下，核心就不依赖 example 中的 dart 文件了

**Comment by hackware1993** [comment]
> 我是用pub依赖的，每次编译都会往build里面插入example

你改用 v1.6.3-stable 试试，我把 example 抽出来了，如果没问题了，你把 Issue 关掉

**Comment by roger66** [comment]
> > 我是用pub依赖的，每次编译都会往build里面插入example
> 
> 你改用 v1.6.3-stable 试试，我把 example 抽出来了，如果没问题了，你把 Issue 关掉

好的，已经没问题了
